### ISSUE TITLE
Google cloud speech has no attribute 'enums'

### ISSUE THREAD

**Issue by MedAmine-SUDO** [ChiragSehra/Transcribing-Long-Phone-Calls-With-Speaker-Diarization-on-Google-Cloud-Speech-To-Text#1]
Hi, I was trying to run the project and I keep getting this error:
Traceback (most recent call last):
  File "./speaker_diarization.py", line 69, in <module>
    transcribe_gcs(args.path)
  File "./speaker_diarization.py", line 18, in transcribe_gcs
    encoding = speech.enums.RecognitionConfig.AudioEncoding.LINEAR16,
AttributeError: module 'google.cloud.speech_v1p1beta1' has no attribute 'enums'

Any help ?

**Comment by ChiragSehra** [comment]
Hey @MedAmine-SUDO , the api was in beta testing when I used it. Probably you need to check the updated documentation for the specific API. Most probably the AudioEncoding might not be accessible with enums attribute.
Here: [Documentation](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1p1beta1).

I would also suggest to upgrade the `google-cloud-speech` package.
